import "./globals.css";
import SmoothScrollWrapper from "@/components/SmoothScrollWrapper";

export const metadata = {
  title: "Innovacion 2025",
  description: "Generated by create next app",
  createdBy: "@benedicti0n | @subhraneel2005 | @Subhamay-Dey"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#0f0f0f]">
      <body>
        <SmoothScrollWrapper>
          {children}
        </SmoothScrollWrapper>
      </body>
    </html>
  );
}
